### ISSUE TITLE
problem with making several window

### ISSUE THREAD

**Issue by nafergo** [ranjian0/building_tool#11]
I can't seem to create several windows in the same wall that look the same. It would be great to create several windows like it does for building levels.
Right now, I create one after the other and because the width seems to be defined % it's not easy to get exactly the same width for a bunch of windows.

**Comment by ranjian0** [comment]
I get this question a lot. Maybe I need to rethink how people use the addon.

To create multiple features on a face, I recommend doing an edge subdivide first (this creates multiple even faces along an axis). Then with the faces selected, apply the feature e.g in your case, windows.

**_NOTE:_**

> A feature of the addon that's not obvious is that it works with one or more faces selected. You can even
> create multiple buildings simultaneously.
> 

This is why most of the tools work only in editmode. My expectation is that since the addon cannot
provide work-flow for all use-cases, you use blender's tools alongside the addon's tools.

If you ever want to create multiple items, consider thinking about how you would do it without the addon
first. Once you think about that, then it's clearer to see what problems the addon solves.
