### ISSUE TITLE
Feature Request - Support for Unit Systems

### ISSUE THREAD

**Issue by Sonario648** [ranjian0/building_tool#114]
Greetings, Lucky, and Ranjan0. I'm super in love with the building tools addon.  I always had plans on making buildings in Blender so I could port them over to other apps I use, like Source Filmmaker, so your building tools add-on is going to help a LOT. 

I do have a couple of feature requests that I think would really make this add-on even more spectacular. I hope you consider them for future updates.

1. I've quickly noticed that the Building Tools Add-on only uses the standard Blender units system instead of also being able to be adapted to the Imperial and Metric Scale in the Units tab under Scene Properties in the Properties Panel. 

Being able to specify how big the building should be using the Imperial and Metric Scales would really help with architecture, as that way we can specify how big we want everything to be instead of winging it with a wild guess.

![image](https://user-images.githubusercontent.com/66429559/83797129-00fd5c00-a69a-11ea-8725-6ba22cc02b73.png)

2.  Adding an option for the dialog in the lower left corner to be up forever as long as you're selecting the part or something would be a good addition, so that way you can always make changes on one part if you change your mind later; for example, setting up the stairs first, then wanting to change them later after you've already set up and are working on something else like the windows. This would also be useful if you want to change the floorplan later on and you don't want to keep having to completely start over. 
![image](https://user-images.githubusercontent.com/66429559/83798893-d6f96900-a69c-11ea-907d-e331c164146e.png)

3. Adding an option for doorknobs, door handles, latches, locks, and keyholes for doors, and blinds/curtains with or without a pull string for windows.

That is all the features I can think of for now for my new favorite Blender add-on. I hope each of them can be a possibility in a future update, especially the metric/imperial scale feature.

Best of luck with future updates! I can't wait to see what's in store for the future!
~Sonario648

**Comment by ranjian0** [comment]
Hi @Sonario648. We appreciate your kind words about the addon.

## 1. Unit Systems

I had always assumed that the addon would adapt to the selected unit system but after fiddling around today it seems that is not the case. Changing values for the addon quickly switched blender back to the Metric System.

I will create a new issue for this.

## 2. Changing previous properties

This issue is difficult to tackle due to blender's internal design. All tools for the addon operate like other normal blender tools like `extrude`. In the same way that blender doesn't quite allow you to change settings of an extrude that was done earlier (without undo-ing), the addon also doesn't support that. 

Unfortunately, this problem cannot be solved without completely abandoning `blender's way` of doing things. This means I would need to develop a whole new system and UI for it. Addons like `archimesh` do this at quite a high price i.e the tools become alien to blender experience.

## 3. Detail Additions

Implementing additional details like this will create a huge workload. The best we can do is give users a convenient way to do this. Issue #95 has a discussion concerning this kind of issue.
